<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/hello.proto

namespace GPBMetadata\Pb;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA7\x01\x0A\x0Epb/hello.proto\x12\x02pb\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1D\x0A\x0AHelloReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x0929\x0A\x07Greeter\x12.\x0A\x08SayHello\x12\x10.pb.HelloRequest\x1A\x0E.pb.HelloReply\"\x00B\x11Z\x0Fgrpc-example/pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

